export enum EffectMetadataType {
    EFFECT_METADATA = 'NGXS__EFFECT_METADATA',
    EFFECT_START_METADATA = 'NGXS__EFFECT_START_METADATA',
    EFFECT_TERMINATE_METADATA = 'NGXS__EFFECT_TERMINATE_METADATA',
}
